export const ENV_KEYS = {
  //Auth
  AUTH_SECRET: 'AUTH_SECRET',
  AUTH_EXPIRATION_MILLS: 'AUTH_EXPIRATION_MILLS',
  AUTH_REFRESH_TOKEN_EXPIRATION_DAYS: 'AUTH_REFRESH_TOKEN_EXPIRATION_DAYS',
  AUTH_BASE_URL: 'AUTH_BASE_URL',
  AUTH_PASSWORD_RESET_URL: 'AUTH_PASSWORD_RESET_URL',
  AUTH_GOOGLE_CLIENT_ID: 'AUTH_GOOGLE_CLIENT_ID',
  AUTH_GOOGLE_SECRET: 'AUTH_GOOGLE_SECRET',
  AUTH_GOOGLE_REDIRECT_URL: 'AUTH_GOOGLE_REDIRECT_URL',
  AUTH_COOKIE_SAME_SITE: 'AUTH_COOKIE_SAME_SITE',
  //Email
  EMAIL_GOOGLE_ID: 'EMAIL_GOOGLE_ID',
  EMAIL_GOOGLE_APP_PASSWD: 'EMAIL_GOOGLE_APP_PASSWD',
  EMAIL_RESET_PASSWD_REDIRECT_URL: 'EMAIL_RESET_PASSWD_REDIRECT_URL',
  //Redis
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  //AWS
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET: 'AWS_S3_BUCKET',
  CLOUDFRONT_DOMAIN: 'CLOUDFRONT_DOMAIN',
} as const;
