export const ENV_KEYS = {
  AUTH_SECRET: 'AUTH_SECRET',
  AUTH_EXPIRATION_MILLS: 'AUTH_EXPIRATION_MILLS',
  AUTH_BASE_URL: 'AUTH_BASE_URL',
  AUTH_PASSWORD_RESET_URL: 'AUTH_PASSWORD_RESET_URL',
  AUTH_GOOGLE_CLIENT_ID: 'AUTH_GOOGLE_CLIENT_ID',
  AUTH_GOOGLE_SECRET: 'AUTH_GOOGLE_SECRET',
  AUTH_GOOGLE_REDIRECT_URL: 'AUTH_GOOGLE_REDIRECT_URL',
  AUTH_COOKIE_SAME_SITE: 'AUTH_COOKIE_SAME_SITE',
} as const;
