export const ENV_KEYS = {
  AUTH_SECRET: 'AUTH_SECRET',
  AUTH_EXPIRATION_MILLS: 'AUTH_EXPIRATION_MILLS',
  AUTH_BASE_URL: 'AUTH_BASE_URL',
  AUTH_PASSWORD_RESET_URL: 'AUTH_PASSWORD_RESET_URL',
} as const;
